project_type: ruby
test:
  bundle-audit:
    command: bundle-audit check --update > .framgia-ci-reports/bundle-audit.txt
    ignore: true
  rspec:
    command: rspec --format html --out .framgia-ci-reports/rspec.html spec/
    ignore: true
  brakeman:
    command: brakeman -o .framgia-ci-reports/brakeman.html -o .framgia-ci-reports/brakeman.json
    ignore: true
  reek:
    command: reek --format html > .framgia-ci-reports/reek.html
    ignore: true
  rubocop:
    command: bundle exec rubocop --require rubocop/formatter/checkstyle_formatter --format RuboCop::Formatter::CheckstyleFormatter --no-color --rails --out .framgia-ci-reports/rubocop.xml app/ lib/
  scss-lint:
    command: scss-lint --require=scss_lint_reporter_checkstyle --format=Checkstyle --out=.framgia-ci-reports/scss-lint.xml app/assets/stylesheets/; ec=$?; if [ $ec -eq 0 -o $ec -eq 1 ]; then (exit 0); else (exit $ec); fi;
    ignore: true
  eslint:
    command: /bin/bash -l -c rake eslint:run_all --format=checkstyle --output-file=.framgia-ci-reports/eslint.xml app/ --ignore-path path::app/assets/javascripts/application.js
  rails_best_practices:
    command: /bin/bash -l -c rails_best_practices -e "db/schema.rb,db/migrate,vendor" --format html --output-file .framgia-ci-reports/rails_best_practices.html app/
    ignore: true
